name: Track Code Changes

on:
  push:
    branches: ["main"]  # Adjust branch as needed

jobs:
  track_changes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install GitPython library
      - name: Install GitPython
        run: pip install gitpython

      # Step 4: Generate a diff report between the last two commits
      - name: Compare Commits and Generate Report
        run: |
          python - <<EOF
          import git

          # Function to generate diff report
          def generate_diff_report():
              # Initialize the repository
              repo = git.Repo(".")

              # Get the last two commits
              commits = list(repo.iter_commits('main', max_count=2))

              # Check if there are at least two commits to compare
              if len(commits) < 2:
                  print("Not enough commits to compare.")
                  with open("diff_report.txt", "w") as report:
                      report.write("Not enough commits to generate a diff.\n")
                  return

              # Get diff between the latest and previous commits
              diff_text = repo.git.diff(commits[1], commits[0], name_status=True)

              # Write the diff to diff_report.txt
              with open("diff_report.txt", "w") as report:
                  if diff_text:
                      report.write(diff_text)
                      print("Diff report generated successfully.")
                  else:
                      report.write("No changes detected between the commits.\n")
                      print("No changes detected between the commits.")

          # Execute the diff report generation
          generate_diff_report()
          EOF

      # Step 5: Upload the generated diff report as an artifact
      - name: Upload Diff Report
        uses: actions/upload-artifact@v3
        with:
          name: Diff Report
          path: diff_report.txt
